image:
  repository: docker.io/fluxcd/flux
  tag: 1.21.0

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 512Mi

clusterRole:
  create: true

memcached:
  enabled: true
  verbose: false

git:
  url: ''
  b