apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mgt-demo
  version: "1.17"
  region: "ap-southeast-2"
  tags:
    Project: mgt-demo
    Environent: dev
    Owner: Chaminda

availabilityZones: ["ap-southeast-2a", "ap-southeast-2b", "ap-southeast-2c"]

vpc:
  cidr: 10.2.0.0/16
  nat:
    gateway: HighlyAvailable
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

iam:
  withOIDC: false

nodeGroups:
  - name: workers1
    instanceType: t3.large
    desiredCapacity: 2
    tags:
      Name: mgt-demo
      Environent: dev
      Owner: chaminda